general.import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]

[font]
size = 14

[font.bold]

family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[scrolling]
history = 10000

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux attach || tmux"] }

[window]
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
